---
- name: " AWS | SUBNET Create {{ item_subnet.name }}"
  ec2_vpc_subnet:
    state: present
    region: "{{ item_vpc.region }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item_subnet.cidr }}"
    az: "{{ item_subnet.az }}"
    map_public: "{{ item_subnet.map_public | d('no') }}"
    resource_tags:
      Name: "{{ item_subnet.name }}"
  register: ret_subnet

- name: AWS | SUBNET set on list
  set_fact:
    vpc_subnets: "{{ vpc_subnets + [item_subnet |combine({'subnet_id':ret_subnet.subnet.id})] }}"
