---
- name: AWS | IGW create
  ec2_vpc_igw:
    state: present
    region: "{{ item_vpc.region }}"
    vpc_id: "{{ vpc_id }}"
    tags:
      Name: "{{ item_vpc.name }}-igw"
  register: ret_igw

- name: AWS | IGW fact
  set_fact:
    vpc_igw: "{{ ret_igw.gateway_id }}"
    gateways: "{{ gateways | combine({'igw':ret_igw.gateway_id}) }}"
    cloud_network_state: "{{ cloud_network_state
        | combine({'igw':ret_igw.gateway_id})
      }}"
