---
- name: AWS | IGW | Create Tag Name
  ansible.builtin.set_fact:
    igw_tag_name: {'Name': item_vpc.name+'-igw'}

- name: AWS | IGW | Create
  amazon.aws.ec2_vpc_igw:
    state: present
    region: "{{ item_vpc.region }}"
    vpc_id: "{{ vpc_id }}"
    tags: "{{ item_vpc.igw.tags | d({}) | combine(igw_tag_name) }}"
    purge_tags: "{{ item_vpc.igw.purge_tags | d('no') }}"
  register: ret_igw
  until: "ret_igw is not failed"
  retries: 5
  delay: 5

- name: AWS | IGW | Save state
  ansible.builtin.set_fact:
    vpc_igw: "{{ ret_igw.gateway_id }}"
    gateways: "{{ gateways | combine({'igw': ret_igw.gateway_id}) }}"
    cloud_network_state: "{{ cloud_network_state
        | combine({'igw': ret_igw.gateway_id})
      }}"
