---
- name: AWS | RT lookup route tables and it's subnets
  set_fact:
    rtbs: "{{ rtbs + [{'name': item, 'subnets': vpc_subnets |json_query(rt_query)|unique }] }}"
  vars:
    rt_query: "[?route=='{{item}}'].subnet_id"
  with_items: "{{ rtbs_vpc |union(subnets_rtbs) |unique }}"

- name: AWS | VPC RT
  include: aws-rtb.yml
  with_items: "{{ item_vpc.routes }}"
  loop_control:
    loop_var: item_rtb

# Associate subnet to its rt
# Associate to public rt an igw
# Associate to private rt an nat_gw
