---

- name: Init state
  set_fact:
    cloud_networks_state: []

- name: start setup the network for a specific provider
  include_tasks: "{{ item_vpc.provider }}.yml"
  with_items: "{{ cloud_networks | d([]) }}"
  loop_control:
    loop_var: item_vpc
