---

- name: Init state var
  ansible.builtin.set_fact:
    cloud_networks_state: []

- name: Start setup the network for a specific provider
  ansible.builtin.include_tasks: "{{ item_vpc.provider }}.yml"
  with_items: "{{ cloud_networks | d([]) }}"
  loop_control:
    loop_var: item_vpc
